force-app/main/default/objects/Country__c/fields/Capital__c.field-meta.xml
<CustomField>
    <fullName>Capital__c</fullName>
    <label>Capital</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Flag_Image__c.field-meta.xml
<CustomField>
    <fullName>Flag_Image__c</fullName>
    <label>Flag Image</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SObjectListHelperTest.cls
@IsTest(seealldata=false)
public class SObjectListHelperTest {

    @IsTest
    static void testExactSplitRecordList(){
        List<Country__c> testCountries = new List<Country__c>();
        for (Integer i = 0; i < 200; i++) {
            Country__c country = new Country__c();
            country.Name = 'Country '+i;
            country.Capital__c = 'Capital ' +i;
            country.Languages__c = 'Languages '+i;
            country.Description__c = 'Test description '+i;
            country.Flag_Image__c = 'url img '+i;
            testCountries.add(country);
        }

        Test.startTest();
            List<List<SObject>> result = SObjectListHelper.splitRecordList(testCountries);
        Test.stopTest();
        
        Assert.areEqual(4, result.size(), 'Expected 4 sublists after splitting');
    }

    @IsTest
    static void testNotExactSplitRecordList(){
        List<Country__c> testCountries = new List<Country__c>();
        for (Integer i = 0; i < 101; i++) {
            Country__c country = new Country__c();
            country.Name = 'Country '+i;
            country.Capital__c = 'Capital ' +i;
            country.Languages__c = 'Languages '+i;
            country.Description__c = 'Test description '+i;
            country.Flag_Image__c = 'url img '+i;
            testCountries.add(country);
        }

        Test.startTest();
            List<List<SObject>> result = SObjectListHelper.splitRecordList(testCountries);
        Test.stopTest();
        
        Assert.areEqual(3, result.size(), 'Expected 3 sublists after splitting');
    }
}